# Generated by Django 3.1 on 2020-10-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_watchers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
