# Generated by Django 3.1 on 2020-10-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='for_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
    ]
