# Generated by Django 3.1 on 2020-10-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_listing',
            new_name='AuctionListing',
        ),
    ]
