# Generated by Django 3.1 on 2020-10-20 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201019_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
